/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.panicker.resolve.pmf.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PMFPromotion extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PMFPromotion\",\"namespace\":\"com.panicker.resolve.pmf.avro\",\"fields\":[{\"name\":\"itemDesc\",\"type\":[\"string\",\"null\"],\"default\":\"\"},{\"name\":\"longDesc\",\"type\":[\"string\",\"null\"],\"default\":\"\"},{\"name\":\"revision\",\"type\":[\"string\",\"null\"],\"default\":\"\"},{\"name\":\"crmProductType\",\"type\":[\"string\",\"null\"],\"default\":\"\"},{\"name\":\"channelClass\",\"type\":[\"string\",\"null\"],\"default\":\"\"},{\"name\":\"fulfillmentType\",\"type\":[\"string\",\"null\"],\"default\":\"\"},{\"name\":\"tariffCode\",\"type\":[\"string\",\"null\"],\"default\":\"\"}]}");
    public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
    @Deprecated public java.lang.CharSequence itemDesc;
    @Deprecated public java.lang.CharSequence longDesc;
    @Deprecated public java.lang.CharSequence revision;
    @Deprecated public java.lang.CharSequence crmProductType;
    @Deprecated public java.lang.CharSequence channelClass;
    @Deprecated public java.lang.CharSequence fulfillmentType;
    @Deprecated public java.lang.CharSequence tariffCode;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public PMFPromotion() {}

    /**
     * All-args constructor.
     */
    public PMFPromotion(java.lang.CharSequence itemDesc, java.lang.CharSequence longDesc, java.lang.CharSequence revision, java.lang.CharSequence crmProductType, java.lang.CharSequence channelClass, java.lang.CharSequence fulfillmentType, java.lang.CharSequence tariffCode) {
        this.itemDesc = itemDesc;
        this.longDesc = longDesc;
        this.revision = revision;
        this.crmProductType = crmProductType;
        this.channelClass = channelClass;
        this.fulfillmentType = fulfillmentType;
        this.tariffCode = tariffCode;
    }

    public org.apache.avro.Schema getSchema() { return SCHEMA$; }
    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0: return itemDesc;
            case 1: return longDesc;
            case 2: return revision;
            case 3: return crmProductType;
            case 4: return channelClass;
            case 5: return fulfillmentType;
            case 6: return tariffCode;
            default: throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }
    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value="unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0: itemDesc = (java.lang.CharSequence)value$; break;
            case 1: longDesc = (java.lang.CharSequence)value$; break;
            case 2: revision = (java.lang.CharSequence)value$; break;
            case 3: crmProductType = (java.lang.CharSequence)value$; break;
            case 4: channelClass = (java.lang.CharSequence)value$; break;
            case 5: fulfillmentType = (java.lang.CharSequence)value$; break;
            case 6: tariffCode = (java.lang.CharSequence)value$; break;
            default: throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    /**
     * Gets the value of the 'itemDesc' field.
     */
    public java.lang.CharSequence getItemDesc() {
        return itemDesc;
    }

    /**
     * Sets the value of the 'itemDesc' field.
     * @param value the value to set.
     */
    public void setItemDesc(java.lang.CharSequence value) {
        this.itemDesc = value;
    }

    /**
     * Gets the value of the 'longDesc' field.
     */
    public java.lang.CharSequence getLongDesc() {
        return longDesc;
    }

    /**
     * Sets the value of the 'longDesc' field.
     * @param value the value to set.
     */
    public void setLongDesc(java.lang.CharSequence value) {
        this.longDesc = value;
    }

    /**
     * Gets the value of the 'revision' field.
     */
    public java.lang.CharSequence getRevision() {
        return revision;
    }

    /**
     * Sets the value of the 'revision' field.
     * @param value the value to set.
     */
    public void setRevision(java.lang.CharSequence value) {
        this.revision = value;
    }

    /**
     * Gets the value of the 'crmProductType' field.
     */
    public java.lang.CharSequence getCrmProductType() {
        return crmProductType;
    }

    /**
     * Sets the value of the 'crmProductType' field.
     * @param value the value to set.
     */
    public void setCrmProductType(java.lang.CharSequence value) {
        this.crmProductType = value;
    }

    /**
     * Gets the value of the 'channelClass' field.
     */
    public java.lang.CharSequence getChannelClass() {
        return channelClass;
    }

    /**
     * Sets the value of the 'channelClass' field.
     * @param value the value to set.
     */
    public void setChannelClass(java.lang.CharSequence value) {
        this.channelClass = value;
    }

    /**
     * Gets the value of the 'fulfillmentType' field.
     */
    public java.lang.CharSequence getFulfillmentType() {
        return fulfillmentType;
    }

    /**
     * Sets the value of the 'fulfillmentType' field.
     * @param value the value to set.
     */
    public void setFulfillmentType(java.lang.CharSequence value) {
        this.fulfillmentType = value;
    }

    /**
     * Gets the value of the 'tariffCode' field.
     */
    public java.lang.CharSequence getTariffCode() {
        return tariffCode;
    }

    /**
     * Sets the value of the 'tariffCode' field.
     * @param value the value to set.
     */
    public void setTariffCode(java.lang.CharSequence value) {
        this.tariffCode = value;
    }

    /** Creates a new PMFPromotion RecordBuilder */
    public static com.panicker.resolve.pmf.avro.PMFPromotion.Builder newBuilder() {
        return new com.panicker.resolve.pmf.avro.PMFPromotion.Builder();
    }

    /** Creates a new PMFPromotion RecordBuilder by copying an existing Builder */
    public static com.panicker.resolve.pmf.avro.PMFPromotion.Builder newBuilder(com.panicker.resolve.pmf.avro.PMFPromotion.Builder other) {
        return new com.panicker.resolve.pmf.avro.PMFPromotion.Builder(other);
    }

    /** Creates a new PMFPromotion RecordBuilder by copying an existing PMFPromotion instance */
    public static com.panicker.resolve.pmf.avro.PMFPromotion.Builder newBuilder(com.panicker.resolve.pmf.avro.PMFPromotion other) {
        return new com.panicker.resolve.pmf.avro.PMFPromotion.Builder(other);
    }

    /**
     * RecordBuilder for PMFPromotion instances.
     */
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PMFPromotion>
            implements org.apache.avro.data.RecordBuilder<PMFPromotion> {

        private java.lang.CharSequence itemDesc;
        private java.lang.CharSequence longDesc;
        private java.lang.CharSequence revision;
        private java.lang.CharSequence crmProductType;
        private java.lang.CharSequence channelClass;
        private java.lang.CharSequence fulfillmentType;
        private java.lang.CharSequence tariffCode;

        /** Creates a new Builder */
        private Builder() {
            super(com.panicker.resolve.pmf.avro.PMFPromotion.SCHEMA$);
        }

        /** Creates a Builder by copying an existing Builder */
        private Builder(com.panicker.resolve.pmf.avro.PMFPromotion.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.itemDesc)) {
                this.itemDesc = data().deepCopy(fields()[0].schema(), other.itemDesc);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.longDesc)) {
                this.longDesc = data().deepCopy(fields()[1].schema(), other.longDesc);
                fieldSetFlags()[1] = true;
            }
            if (isValidValue(fields()[2], other.revision)) {
                this.revision = data().deepCopy(fields()[2].schema(), other.revision);
                fieldSetFlags()[2] = true;
            }
            if (isValidValue(fields()[3], other.crmProductType)) {
                this.crmProductType = data().deepCopy(fields()[3].schema(), other.crmProductType);
                fieldSetFlags()[3] = true;
            }
            if (isValidValue(fields()[4], other.channelClass)) {
                this.channelClass = data().deepCopy(fields()[4].schema(), other.channelClass);
                fieldSetFlags()[4] = true;
            }
            if (isValidValue(fields()[5], other.fulfillmentType)) {
                this.fulfillmentType = data().deepCopy(fields()[5].schema(), other.fulfillmentType);
                fieldSetFlags()[5] = true;
            }
            if (isValidValue(fields()[6], other.tariffCode)) {
                this.tariffCode = data().deepCopy(fields()[6].schema(), other.tariffCode);
                fieldSetFlags()[6] = true;
            }
        }

        /** Creates a Builder by copying an existing PMFPromotion instance */
        private Builder(com.panicker.resolve.pmf.avro.PMFPromotion other) {
            super(com.panicker.resolve.pmf.avro.PMFPromotion.SCHEMA$);
            if (isValidValue(fields()[0], other.itemDesc)) {
                this.itemDesc = data().deepCopy(fields()[0].schema(), other.itemDesc);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.longDesc)) {
                this.longDesc = data().deepCopy(fields()[1].schema(), other.longDesc);
                fieldSetFlags()[1] = true;
            }
            if (isValidValue(fields()[2], other.revision)) {
                this.revision = data().deepCopy(fields()[2].schema(), other.revision);
                fieldSetFlags()[2] = true;
            }
            if (isValidValue(fields()[3], other.crmProductType)) {
                this.crmProductType = data().deepCopy(fields()[3].schema(), other.crmProductType);
                fieldSetFlags()[3] = true;
            }
            if (isValidValue(fields()[4], other.channelClass)) {
                this.channelClass = data().deepCopy(fields()[4].schema(), other.channelClass);
                fieldSetFlags()[4] = true;
            }
            if (isValidValue(fields()[5], other.fulfillmentType)) {
                this.fulfillmentType = data().deepCopy(fields()[5].schema(), other.fulfillmentType);
                fieldSetFlags()[5] = true;
            }
            if (isValidValue(fields()[6], other.tariffCode)) {
                this.tariffCode = data().deepCopy(fields()[6].schema(), other.tariffCode);
                fieldSetFlags()[6] = true;
            }
        }

        /** Gets the value of the 'itemDesc' field */
        public java.lang.CharSequence getItemDesc() {
            return itemDesc;
        }

        /** Sets the value of the 'itemDesc' field */
        public com.panicker.resolve.pmf.avro.PMFPromotion.Builder setItemDesc(java.lang.CharSequence value) {
            validate(fields()[0], value);
            this.itemDesc = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /** Checks whether the 'itemDesc' field has been set */
        public boolean hasItemDesc() {
            return fieldSetFlags()[0];
        }

        /** Clears the value of the 'itemDesc' field */
        public com.panicker.resolve.pmf.avro.PMFPromotion.Builder clearItemDesc() {
            itemDesc = null;
            fieldSetFlags()[0] = false;
            return this;
        }

        /** Gets the value of the 'longDesc' field */
        public java.lang.CharSequence getLongDesc() {
            return longDesc;
        }

        /** Sets the value of the 'longDesc' field */
        public com.panicker.resolve.pmf.avro.PMFPromotion.Builder setLongDesc(java.lang.CharSequence value) {
            validate(fields()[1], value);
            this.longDesc = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /** Checks whether the 'longDesc' field has been set */
        public boolean hasLongDesc() {
            return fieldSetFlags()[1];
        }

        /** Clears the value of the 'longDesc' field */
        public com.panicker.resolve.pmf.avro.PMFPromotion.Builder clearLongDesc() {
            longDesc = null;
            fieldSetFlags()[1] = false;
            return this;
        }

        /** Gets the value of the 'revision' field */
        public java.lang.CharSequence getRevision() {
            return revision;
        }

        /** Sets the value of the 'revision' field */
        public com.panicker.resolve.pmf.avro.PMFPromotion.Builder setRevision(java.lang.CharSequence value) {
            validate(fields()[2], value);
            this.revision = value;
            fieldSetFlags()[2] = true;
            return this;
        }

        /** Checks whether the 'revision' field has been set */
        public boolean hasRevision() {
            return fieldSetFlags()[2];
        }

        /** Clears the value of the 'revision' field */
        public com.panicker.resolve.pmf.avro.PMFPromotion.Builder clearRevision() {
            revision = null;
            fieldSetFlags()[2] = false;
            return this;
        }

        /** Gets the value of the 'crmProductType' field */
        public java.lang.CharSequence getCrmProductType() {
            return crmProductType;
        }

        /** Sets the value of the 'crmProductType' field */
        public com.panicker.resolve.pmf.avro.PMFPromotion.Builder setCrmProductType(java.lang.CharSequence value) {
            validate(fields()[3], value);
            this.crmProductType = value;
            fieldSetFlags()[3] = true;
            return this;
        }

        /** Checks whether the 'crmProductType' field has been set */
        public boolean hasCrmProductType() {
            return fieldSetFlags()[3];
        }

        /** Clears the value of the 'crmProductType' field */
        public com.panicker.resolve.pmf.avro.PMFPromotion.Builder clearCrmProductType() {
            crmProductType = null;
            fieldSetFlags()[3] = false;
            return this;
        }

        /** Gets the value of the 'channelClass' field */
        public java.lang.CharSequence getChannelClass() {
            return channelClass;
        }

        /** Sets the value of the 'channelClass' field */
        public com.panicker.resolve.pmf.avro.PMFPromotion.Builder setChannelClass(java.lang.CharSequence value) {
            validate(fields()[4], value);
            this.channelClass = value;
            fieldSetFlags()[4] = true;
            return this;
        }

        /** Checks whether the 'channelClass' field has been set */
        public boolean hasChannelClass() {
            return fieldSetFlags()[4];
        }

        /** Clears the value of the 'channelClass' field */
        public com.panicker.resolve.pmf.avro.PMFPromotion.Builder clearChannelClass() {
            channelClass = null;
            fieldSetFlags()[4] = false;
            return this;
        }

        /** Gets the value of the 'fulfillmentType' field */
        public java.lang.CharSequence getFulfillmentType() {
            return fulfillmentType;
        }

        /** Sets the value of the 'fulfillmentType' field */
        public com.panicker.resolve.pmf.avro.PMFPromotion.Builder setFulfillmentType(java.lang.CharSequence value) {
            validate(fields()[5], value);
            this.fulfillmentType = value;
            fieldSetFlags()[5] = true;
            return this;
        }

        /** Checks whether the 'fulfillmentType' field has been set */
        public boolean hasFulfillmentType() {
            return fieldSetFlags()[5];
        }

        /** Clears the value of the 'fulfillmentType' field */
        public com.panicker.resolve.pmf.avro.PMFPromotion.Builder clearFulfillmentType() {
            fulfillmentType = null;
            fieldSetFlags()[5] = false;
            return this;
        }

        /** Gets the value of the 'tariffCode' field */
        public java.lang.CharSequence getTariffCode() {
            return tariffCode;
        }

        /** Sets the value of the 'tariffCode' field */
        public com.panicker.resolve.pmf.avro.PMFPromotion.Builder setTariffCode(java.lang.CharSequence value) {
            validate(fields()[6], value);
            this.tariffCode = value;
            fieldSetFlags()[6] = true;
            return this;
        }

        /** Checks whether the 'tariffCode' field has been set */
        public boolean hasTariffCode() {
            return fieldSetFlags()[6];
        }

        /** Clears the value of the 'tariffCode' field */
        public com.panicker.resolve.pmf.avro.PMFPromotion.Builder clearTariffCode() {
            tariffCode = null;
            fieldSetFlags()[6] = false;
            return this;
        }

        @Override
        public PMFPromotion build() {
            try {
                PMFPromotion record = new PMFPromotion();
                record.itemDesc = fieldSetFlags()[0] ? this.itemDesc : (java.lang.CharSequence) defaultValue(fields()[0]);
                record.longDesc = fieldSetFlags()[1] ? this.longDesc : (java.lang.CharSequence) defaultValue(fields()[1]);
                record.revision = fieldSetFlags()[2] ? this.revision : (java.lang.CharSequence) defaultValue(fields()[2]);
                record.crmProductType = fieldSetFlags()[3] ? this.crmProductType : (java.lang.CharSequence) defaultValue(fields()[3]);
                record.channelClass = fieldSetFlags()[4] ? this.channelClass : (java.lang.CharSequence) defaultValue(fields()[4]);
                record.fulfillmentType = fieldSetFlags()[5] ? this.fulfillmentType : (java.lang.CharSequence) defaultValue(fields()[5]);
                record.tariffCode = fieldSetFlags()[6] ? this.tariffCode : (java.lang.CharSequence) defaultValue(fields()[6]);
                return record;
            } catch (Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }
}
